### ISSUE TITLE
Getters appeneded with a null

### ISSUE THREAD

**Issue by joshpetit** [nerdrew/dart-ctags#11]
Hey thanks for creating this, it makes my workflow so much more bearable! I noticed that for getters such as this:
```dart
  List<Item> get list {
}
```
or this
```dart
  List<Item> get list => [...];
```
that in my tag bar I find the word `null` appended at the end. Like this: `   +listnull : List<Item>`. I'm not sure if this is due to dart-ctags not parsing the fact that dart getters don't have parameters or if it is Tagbar that is the problem. 

This is something minor though obviously, thanks again for creating this!

**Comment by jrc2139** [comment]
i believe i fixed this in [#f21d19](https://github.com/nerdrew/dart-ctags/commit/f21d1994b68e0da9b6ff5885d4cf453f0150364c)

are you sure you're on the latest version?

**Comment by joshpetit** [comment]
Huh that's weird, I installed it after that point. Whatever the case I reinstalled and it works fine now, thanks!
