### ISSUE TITLE
Un-checked null when generating tags for protobuf library

### ISSUE THREAD

**Issue by ghost** [nerdrew/dart-ctags#2]
Command to reproduce: 
pub global run dart_ctags:tags  -o .git/tags packages/protobuf

Stack Trace:
Unhandled exception:
Uncaught Error: The null object does not have a method '[]'.

NoSuchMethodError: method not found: '[]'
Receiver: null
Arguments: [0]
Stack Trace:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#1      Ctags.parseFile.<anonymous closure>.<anonymous closure> (http://localhost:53485/tags.dart:102)
#2      Object&ListMixin.forEach (dart:collection/list.dart:63)
#3      Ctags.parseFile.<anonymous closure> (http://localhost:53485/tags.dart:96)
#4      Object&ListMixin.forEach (dart:collection/list.dart:63)
#5      Ctags.parseFile (http://localhost:53485/tags.dart:79)
#6      addFileSystemEntity.<anonymous closure> (http://localhost:53485/tags.dart:52)
#7      _MapStream._handleData (dart:async/stream_pipe.dart:235)
#8      _handleData (dart:async/stream_pipe.dart:172)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#12     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:590)
#13     _StreamController._add (dart:async/stream_controller.dart:465)
#14     _StreamController.add (dart:async/stream_controller.dart:412)
#15     _AsyncDirectoryLister.next.<anonymous closure> (dart:io/directory_impl.dart:328)
#16     _RootZone.runUnary (dart:async/zone.dart:1155)
#17     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#18     _Future._propagateToListeners (dart:async/future_impl.dart:567)
#19     _Future._completeWithValue (dart:async/future_impl.dart:358)
#20     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
#21     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#22     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)

pubspec.lock
  protobuf:
    description: protobuf
    source: hosted
    version: "0.3.5+2"

The issue is caused by the following line:
constructor.matchAsPrefix(member.toSource())[0]

It can be worked around by checking if the return is null before indexing it, but there may be a better fix.

**Comment by nerdrew** [comment]
I just published `0.0.2` on pub. Want to test it? https://pub.dartlang.org/packages/dart_ctags

**Comment by ghost** [comment]
Just tested it and it's working now. Cheers!
