### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by emmanuelcohenlaroque** [nerdrew/dart-ctags#7]
I cannot run on Dart Dart VM version: 2.8.4 (stable) (Unknown timestamp) on "linux_x64"
I get the following exception when trying to generate ctags for the local project: 
Thanks

~/.pub-cache/bin/dart_ctags -l -o .git/ctags 

Unhandled exception:
Invalid argument(s): Content produced diagnostics when parsed
#0      parseString (package:analyzer/dart/analysis/utilities.dart:131)
#1      parseFile (package:analyzer/dart/analysis/utilities.dart:52)
#2      Ctags.parseFile (file:///home/ecl/.pub-cache/hosted/pub.dartlang.org/dart_ctags-1.0.0/bin/tags.dart:110)
#3      Ctags.addFileSystemEntity (file:///home/ecl/.pub-cache/hosted/pub.dartlang.org/dart_ctags-1.0.0/bin/tags.dart:87)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:417)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:346)
#6      Future.wait (dart:async/future.dart:395)
#7      Ctags.generate (file:///home/ecl/.pub-cache/hosted/pub.dartlang.org/dart_ctags-1.0.0/bin/tags.dart:56)
#8      main (file:///home/ecl/.pub-cache/hosted/pub.dartlang.org/dart_ctags-1.0.0/bin/tags.dart:292)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168

**Comment by jrc2139** [comment]
that usually means some dart file in the directory has a syntax error.  we should work on handling that error gracefully!

**Comment by emmanuelcohenlaroque** [comment]
Thanks! Interesting as that code is compiling ok. Is there any possibility to get the name of that culprit file? CheersLe 1 juil. 2020 21:47, jrc2139 <notifications@github.com> a écrit :
that usually means some dart file in the directory has a syntax error.  we should work on handling that error gracefully!

**Comment by jrc2139** [comment]
yeah there must be a way.. I'll take a look this wknd

**Comment by emmanuelcohenlaroque** [comment]
Thanks heaps!Le 2 juil. 2020 10:08, jrc2139 <notifications@github.com> a écrit :
yeah there must be a way.. I'll take a look this wknd

**Comment by jrc2139** [comment]
#8 i made a PR for it.. you could just download my repo and use it in the meantime!

**Comment by emmanuelcohenlaroque** [comment]
Great work! Cheers.
